usedItemId = [
    {
       thumb: `./img/used01_01.jpg`,
       name: `모모`,
       caption: `- 비룡소 걸작선 13`,
       newListPrice: `12,000원`,
       newPrice: `10,800원 + 마일리지 600원`,
       usedDirect: `5,600원 (최저가)`,
       usedStore: `5,400원 (최저가)`,
       usedSeller: `490원 (최저가)`,
       bestProduct: `1,100원`,
       betterProduct: `1,100원`,
       goodProduct:`1,100원` 
    },
    {
       thumb: `./img/used01_02.jpg`,
       name: `나미야 잡화점의 기적`,
       caption: ``,
       newListPrice: `14,800원 `,
       newPrice: `13,320원 + 마일리지 740원`,
       usedDirect: `9,400원 (최저가)`,
       usedStore: `9,400원 (최저가)`,
       usedSeller: `1,000원 (최저가)`,
       bestProduct: `1,400원`,
       betterProduct: `1,400원`,
       goodProduct:`1,400원` 
    },
    {
       thumb: `./img/used01_03.jpg`,
       name: `연금술사`,
       caption: ``,
       newListPrice: `12,000원`,
       newPrice: `10,800원 + 마일리지 600원`,
       usedDirect: `4,100원 (최저가)`,
       usedStore: `4,700원 (최저가)`,
       usedSeller: `700원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used01_04.jpg`,
       name: `마사코의 질문`,
       caption: `- 개정판, 6학년 2학기 읽기 수록도서`,
       newListPrice: `13,800원`,
       newPrice: `12,420원 + 마일리지 690원`,
       usedDirect: `6,400원 (최저가)`,
       usedStore: `5,000원 (최저가)`,
       usedSeller: `2,000원 (최저가)`,
       bestProduct: `1,300원`,
       betterProduct: `1,300원`,
       goodProduct:`1,300원` 
    },
    {
       thumb: `./img/used02_01.jpg`,
       name: `인생수업 `,
       caption: `- 잘 물든 단풍은 봄꽃보다 아름답다`,
       newListPrice: `13,000원 `,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `8,100원 (최저가)`,
       usedStore: `5,800원 (최저가)`,
       usedSeller: `300원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used02_02.jpg`,
       name: `공터에서`,
       caption: ``,
       newListPrice: `16,000원`,
       newPrice: `14,400원 + 마일리지 800원`,
       usedDirect: `7,500원 (최저가)`,
       usedStore: `6,300원 (최저가)`,
       usedSeller: `900원 (최저가)`,
       bestProduct: `1,500원`,
       betterProduct: `1,500원`,
       goodProduct:`1,500원` 
    },
    {
       thumb: `./img/used02_03.jpg`,
       name: `백광`,
       caption: ``,
       newListPrice: `14,500원`,
       newPrice: `13,050원 + 마일리지 720원`,
       usedDirect: `8,700원 (최저가)`,
       usedStore: `10,200원 (최저가)`,
       usedSeller: `7,600원 (최저가)`,
       bestProduct: `5,700원`,
       betterProduct: `5,100원`,
       goodProduct: `4,500원`
    },
    {
       thumb: `./img/used02_04.jpg`,
       name: `공무도하`,
       caption: ``,
       newListPrice: `13,000원 `,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `5,700원 (최저가)`,
       usedStore: `5,500원 (최저가)`,
       usedSeller: `400원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used03_01.jpg`,
       name: `완전한 행복`,
       caption: ``,
       newListPrice: `15,800원`,
       newPrice: `14,220원 + 마일리지 790원`,
       usedDirect: `9,500원 (최저가)`,
       usedStore: `11,100원 (최저가)`,
       usedSeller: `4,900원 (최저가)`,
       bestProduct: `1,500원`,
       betterProduct: `1,500원`,
       goodProduct:`1,500원` 
    },
    {
       thumb: `./img/used03_02.jpg`,
       name: `7년의 밤`,
       caption: ``,
       newListPrice: `14,500원`,
       newPrice: `13,050원 + 마일리지 720원`,
       usedDirect: `7,300원 (최저가)`,
       usedStore: `7,200원 (최저가)`,
       usedSeller: `500원 (최저가)`,
       bestProduct: `1,400원`,
       betterProduct: `1,400원`,
       goodProduct:`1,400원` 
    },
    {
       thumb: `./img/used03_03.jpg`,
       name: `내 심장을 쏴라`,
       caption: ``,
       newListPrice: `11,000원`,
       newPrice: `5,000원 + 마일리지 0원`,
       usedDirect: `-`,
       usedStore: `-`,
       usedSeller: `4,900원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used03_04.jpg`,
       name: `내 인생의 스프링 캠프 `,
       caption: `블루픽션 (비룡소 청소년 문학선) 22`,
       newListPrice: `11,000원`,
       newPrice: `9,900원 + 마일리지 550원`,
       usedDirect: `5,400원 (최저가)`,
       usedStore: `5,000원 (최저가)`,
       usedSeller: `750원 (최저가)`,
       bestProduct: `1,000원`,
       betterProduct: `1,000원`,
       goodProduct:`1,000원` 
    },
    {
       thumb: `./img/used04_01.jpg`,
       name: `대한민국 대통령들의 한국경제 이야기 1 `,
       caption: `- 이승만 대통령부터 전두환 대통령까지 산업화 40년`,
       newListPrice: `4,800원`,
       newPrice: `4,320원 + 마일리지 240원`,
       usedDirect: `-`,
       usedStore: `2,400원 (최저가)`,
       usedSeller: `2,300원 (최저가)`,
       bestProduct: `400원`,
       betterProduct: `400원`,
       goodProduct:`400원` 
    },
    {
       thumb: `./img/used04_02.jpg`,
       name: `마법천자문 1 개정판`,
       caption: `- 불어라! 바람 풍(風)`,
       newListPrice: `14,000원 `,
       newPrice: `12,600원 + 마일리지 700원`,
       usedDirect: `5,700원 (최저가)`,
       usedStore: `5,400원 (최저가)`,
       usedSeller: `3,400원 (최저가)`,
       bestProduct: `2,700원`,
       betterProduct: `2,400원`,
       goodProduct: `2,200원`
    },
    {
       thumb: `./img/used04_03.jpg`,
       name: `퀴즈쇼`,
       caption: ``,
       newListPrice: `11,000원 (품절) `,
       newPrice: `9,900원 + 마일리지 550원`,
       usedDirect: `5,900원 (최저가)`,
       usedStore: `4,600원 (최저가)`,
       usedSeller: `1,450원 (최저가)`,
       bestProduct: `1,000원`,
       betterProduct: `1,000원`,
       goodProduct:`1,000원` 
    },
    {
       thumb: `./img/used04_04.jpg`,
       name: `너도 하늘말나리야 `,
       caption: `- 책 읽는 가족 1, 아동용`,
       newListPrice: `7,800원 (절판) `,
       newPrice: `7,020원 + 마일리지 390원`,
       usedDirect: `-`,
       usedStore: `3,700원 (최저가)`,
       usedSeller: `450원 (최저가)`,
       bestProduct: `700원`,
       betterProduct: `700원`,
       goodProduct:`700원` 
    },
    {
       thumb: `./img/used05_01.jpg`,
       name: `What's the Time, Mr Wolf? `,
       caption: ``,
       newListPrice: `18,000원`,
       newPrice: `14,400원 + 마일리지 720원`,
       usedDirect: `8,300원 (최저가)`,
       usedStore: `7,800원 (최저가)`,
       usedSeller: `1,000원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used05_02.jpg`,
       name: `Go Away, Big Green Monster!`,
       caption: ``,
       newListPrice: `18,100원`,
       newPrice: `14,480원 + 마일리지 440원`,
       usedDirect: `10,400원 (최저가)`,
       usedStore: `8,000원 (최저가)`,
       usedSeller: `700원 (최저가)`,
       bestProduct: `1,100원`,
       betterProduct: `1,100원`,
       goodProduct:`1,100원` 
    },
    {
       thumb: `./img/used05_03.jpg`,
       name: `Dr. Seuss's ABC : Blue Back Book `,
       caption: ``,
       newListPrice: `12,120원 (품절)`,
       newPrice: `9,930원 + 마일리지 500원`,
       usedDirect: `4,900원 (최저가)`,
       usedStore: `3,000원 (최저가)`,
       usedSeller: `500원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used05_04.jpg`,
       name: `I am the Music Man`,
       caption: ``,
       newListPrice: `14,150원`,
       newPrice: `11,600원 + 마일리지 580원`,
       usedDirect: `5,000원 (최저가)`,
       usedStore: `2,700원 (최저가)`,
       usedSeller: `300원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used06_01.jpg`,
       name: `방탄소년단 - Skool Luv Affair Special Addition [CD+2DVD][재발매]`,
       caption: `- 포토북(100p)+포토카드(1종)`,
       newListPrice: `47,200원`,
       newPrice: `39,400원 + 마일리지 400원`,
       usedDirect: `17,600원 (최저가)`,
       usedStore: `20,500원 (최저가)`,
       usedSeller: `21,500원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used06_02.jpg`,
       name: `[총공팀 공구](JEWEL)스트레이 키즈 - 미니앨범 ODDINARY`,
       caption: ``,
       newListPrice: `14,300원 (품절)`,
       newPrice: `10,200원 + 마일리지 100원`,
       usedDirect: `7,400원 (최저가)`,
       usedStore: `-`,
       usedSeller: `-`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used06_03.jpg`,
       name: `뉴이스트 W - WHO, YOU [버전 2종 중 랜덤발송](CD알판 버전별 4종 중 랜덤삽입)`,
       caption: `- 포토북(96p)+포토카드(1종)+셀피포토카드(1종)`,
       newListPrice: `18,700원`,
       newPrice: `15,600원 + 마일리지 160원`,
       usedDirect: `7,800원 (최저가)`,
       usedStore: `7,800원 (최저가)`,
       usedSeller: `470원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used06_04.jpg`,
       name: `박지훈 - 정규 1집 MESSAGE [ME Ver.] `,
       caption: `- 포토북(80p)+폴디드 포스터(1종)+MOTD카드(1종)+ASK포토카드(1종)+데코스티커(1종)`,
       newListPrice: `24,900원 `,
       newPrice: `20,800원 + 마일리지 210원`,
       usedDirect: `6,500원 (최저가)`,
       usedStore: `8,500원 (최저가)`,
       usedSeller: `5,000원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used07_01.jpg`,
       name: `조국의 시간`,
       caption: `- 아픔과 진실 말하지 못한 생각`,
       newListPrice: `17,000원`,
       newPrice: `15,300원 + 마일리지 850원`,
       usedDirect: `11,400원 (최저가)`,
       usedStore: `11,900원 (최저가)`,
       usedSeller: `1,000원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used07_02.jpg`,
       name: `달러구트 꿈 백화점`,
       caption: `- 주문하신 꿈은 매진입니다`,
       newListPrice: `13,800원 (품절) `,
       newPrice: `12,420원 + 마일리지 690원`,
       usedDirect: `-`,
       usedStore: `8,700원 (최저가)`,
       usedSeller: `4,500원 (최저가)`,
       bestProduct: `1,300원`,
       betterProduct: `1,300원`,
       goodProduct:`1,300원` 
    },
    {
       thumb: `./img/used07_03.jpg`,
       name: `달러구트 꿈 백화점 2`,
       caption: `- 단골손님을 찾습니다`,
       newListPrice: `13,800원 (품절)`,
       newPrice: `12,420원 + 마일리지 690원`,
       usedDirect: `-`,
       usedStore: `7,700원 (최저가)`,
       usedSeller: `6,000원 (최저가)`,
       bestProduct: `6,200원`,
       betterProduct: `5,500원`,
       goodProduct: `4,900원`
    },
    {
       thumb: `./img/used07_04.jpg`,
       name: `주린이가 가장 알고 싶은 최다질문 TOP77`,
       caption: ``,
       newListPrice: `18,000원`,
       newPrice: `16,200원 + 마일리지 900원`,
       usedDirect: `11,400원 (최저가)`,
       usedStore: `11,200원 (최저가)`,
       usedSeller: `5,400원 (최저가)`,
       bestProduct: `5,900원`,
       betterProduct: `5,300원`,
       goodProduct: `4,700원`
    },
    {
       thumb: `./img/used08_01.jpg`,
       name: `해커스 토익 기출 보카 TOEIC VOCA 단어장`,
       caption: `- 주제별 연상암기로 토익 영단어 30일 완성! | 토익 최신 기출 단어 · 어휘 + 출제포인트 수록 | 토익 RC, LC 필수 단어장, 최신개정판 `,
       newListPrice: `12,900원`,
       newPrice: `11,610원 + 마일리지 640원`,
       usedDirect: `-`,
       usedStore: `8,200원 (최저가)`,
       usedSeller: `6,600원 (최저가)`,
       bestProduct: `5,800원`,
       betterProduct: `5,200원`,
       goodProduct: `4,600원`
    },
    {
       thumb: `./img/used08_03.jpg`,
       name: `보건교사 안은영 (특별판) `,
       caption: ``,
       newListPrice: `14,000원`,
       newPrice: `12,600원 + 마일리지 700원`,
       usedDirect: `8,700원 (최저가)`,
       usedStore: `7,500원 (최저가)`,
       usedSeller: `3,500원 (최저가)`,
       bestProduct: `4,600원`,
       betterProduct: `4,100원`,
       goodProduct: `3,700원`
    },
    {
       thumb: `./img/used08_04.jpg`,
       name: `마음챙김의 시`,
       caption: ``,
       newListPrice: `13,000원`,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `-`,
       usedStore: `7,800원 (최저가)`,
       usedSeller: `6,000원 (최저가)`,
       bestProduct: `5,800원`,
       betterProduct: `5,200원`,
       goodProduct: `4,600원`
    },
    {
       thumb: `./img/used09_01.jpg`,
       name: `여행의 이유 `,
       caption: `- 김영하 산문`,
       newListPrice: `13,500원`,
       newPrice: `12,150원 + 마일리지 670원`,
       usedDirect: `7,200원 (최저가)`,
       usedStore: `8,600원 (최저가)`,
       usedSeller: `4,000원 (최저가)`,
       bestProduct: `1,300원`,
       betterProduct: `1,300원`,
       goodProduct:`1,300원` 
    },
    {
       thumb: `./img/used09_02.jpg`,
       name: `공부머리 독서법 `,
       caption: `- 실현 가능하고 지속 가능한 독서교육의 모든 것`,
       newListPrice: `16,500원`,
       newPrice: `14,850원 + 마일리지 820원`,
       usedDirect: `9,200원 (최저가)`,
       usedStore: `9,700원 (최저가)`,
       usedSeller: `6,500원 (최저가)`,
       bestProduct: `1,600원`,
       betterProduct: `1,600원`,
       goodProduct:`1,600원` 
    },
    {
       thumb: `./img/used09_03.jpg`,
       name: `오늘도 펭수 내일도 펭수`,
       caption: ``,
       newListPrice: `17,000원`,
       newPrice: `15,300원 + 마일리지 850원`,
       usedDirect: `-`,
       usedStore: `11,900원 (최저가)`,
       usedSeller: `800원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used09_04.jpg`,
       name: `아주 작은 습관의 힘`,
       caption: `- 최고의 변화는 어떻게 만들어지는가`,
       newListPrice: `16,000원 `,
       newPrice: `14,400원 + 마일리지 800원`,
       usedDirect: `10,000원 (최저가)`,
       usedStore: `10,100원 (최저가)`,
       usedSeller: `10,700원 (최저가)`,
       bestProduct: `7,200원`,
       betterProduct: `6,400원`,
       goodProduct: `5,700원`
    },
    {
       thumb: `./img/used10_01.jpg`,
       name: `82년생 김지영`,
       caption: `오늘의 젊은 작가 13`,
       newListPrice: `13,000원`,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `7,200원 (최저가)`,
       usedStore: `6,100원 (최저가)`,
       usedSeller: `6,100원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used10_02.jpg`,
       name: `역사의 역사`,
       caption: `- History of Writing History`,
       newListPrice: `16,000원`,
       newPrice: `14,400원 + 마일리지 800원`,
       usedDirect: `9,600원 (최저가)`,
       usedStore: `9,100원 (최저가)`,
       usedSeller: `1,000원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used10_03.jpg`,
       name: `무례한 사람에게 웃으며 대처하는 법`,
       caption: `- 인생자체는 긍정적으로, 개소리에는 단호하게! `,
       newListPrice: `13,800원`,
       newPrice: `12,420원 + 마일리지 690원`,
       usedDirect: `8,100원 (최저가)`,
       usedStore: `7,200원 (최저가)`,
       usedSeller: `1,500원 (최저가)`,
       bestProduct: `1,300원`,
       betterProduct: `1,300원`,
       goodProduct:`1,300원` 
    },
    {
       thumb: `./img/used10_04.jpg`,
       name: `죽고 싶지만 떡볶이는 먹고 싶어`,
       caption: `죽고 싶지만 떡볶이는 먹고 싶어 1`,
       newListPrice: `13,800원`,
       newPrice: `12,420원 + 마일리지 690원`,
       usedDirect: `7,700원 (최저가)`,
       usedStore: `7,200원 (최저가)`,
       usedSeller: `990원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used11_01.jpg`,
       name: `11마리 고양이와 별난 고양이`,
       caption: `11마리 고양이 시리즈 5`,
       newListPrice: `9,000원`,
       newPrice: `8,100원 + 마일리지 450원`,
       usedDirect: `-`,
       usedStore: `4,100원 (최저가)`,
       usedSeller: `1,300원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used11_02.jpg`,
       name: `마틴 루터 킹 `,
       caption: `창비아동문고 138`,
       newListPrice: `10,800원 `,
       newPrice: `9,720원 + 마일리지 540원`,
       usedDirect: `4,200원 (최저가)`,
       usedStore: `2,900원 (최저가)`,
       usedSeller: `500원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used11_03.jpg`,
       name: `아무도 미워하지 않는 자의 죽음`,
       caption: `미네르바의 올빼미 4`,
       newListPrice: `6,500원 (절판) `,
       newPrice: `5,850원 + 마일리지 320원`,
       usedDirect: `3,300원 (최저가)`,
       usedStore: `3,200원 (최저가)`,
       usedSeller: `850원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used11_04.jpg`,
       name: `테라피 하우스`,
       caption: ``,
       newListPrice: `10원`,
       newPrice: `500원 + 마일리지 0원`,
       usedDirect: `-`,
       usedStore: `-`,
       usedSeller: `500원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used12_01.jpg`,
       name: `코끼리가 떴다`,
       caption: ``,
       newListPrice: `12,000원`,
       newPrice: `10,800원 + 마일리지 600원`,
       usedDirect: `-`,
       usedStore: `5,100원 (최저가)`,
       usedSeller: `900원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used12_02.jpg`,
       name: `내 생애 최고의 1년`,
       caption: `- 당신의 인생을 바꿔 줄 가슴 뛰는 1년을 시작하라! `,
       newListPrice: `12,000원 (품절) `,
       newPrice: `10,800원 + 마일리지 600원`,
       usedDirect: `-`,
       usedStore: `4,700원 (최저가)`,
       usedSeller: `900원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used12_03.jpg`,
       name: `그 때 나는 열한 살이었다 `,
       caption: `- 뿔 달린 아이들`,
       newListPrice: `8,500원`,
       newPrice: `7,650원 + 마일리지 420원`,
       usedDirect: `4,200원 (최저가)`,
       usedStore: `3,700원 (최저가)`,
       usedSeller: `1,900원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used12_04.jpg`,
       name: `공작도감`,
       caption: `- 장난감을 만들며 놀자! `,
       newListPrice: `9,800원 `,
       newPrice: `8,820원 + 마일리지 490원`,
       usedDirect: `-`,
       usedStore: `4,900원 (최저가)`,
       usedSeller: `1,980원 (최저가)`,
       bestProduct: `900원`,
       betterProduct: `900원`,
       goodProduct:`900원` 
    },
    {
       thumb: `./img/used13_01.jpg`,
       name: `꼬리를 돌려 주세요`,
       caption: `네버랜드 Picture Books 세계의 걸작 그림책 135`,
       newListPrice: `10,000원 `,
       newPrice: `9,000원 + 마일리지 500원`,
       usedDirect: `-`,
       usedStore: `4,600원 (최저가)`,
       usedSeller: `2,000원 (최저가)`,
       bestProduct: `900원`,
       betterProduct: `900원`,
       goodProduct:`900원` 
    },
    {
       thumb: `./img/used13_02.jpg`,
       name: `공정 : 내가 케이크를 나눈다면 `,
       caption: `질문하는 어린이 1`,
       newListPrice: `13,000원 `,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `7,400원 (최저가)`,
       usedStore: `7,100원 (최저가)`,
       usedSeller: `4,200원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    },
    {
       thumb: `./img/used13_03.jpg`,
       name: `엄마는 절대 모르는 10대 속마음 `,
       caption: `- 사춘기 딸이 묻고 심리학자 엄마가 답하다`,
       newListPrice: `13,000원`,
       newPrice: `11,700원 + 마일리지 650원`,
       usedDirect: `-`,
       usedStore: `5,800원 (최저가)`,
       usedSeller: `1,900원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct: `-`
    },
    {
       thumb: `./img/used13_04.jpg`,
       name: `베드로 엽서`,
       caption: ``,
       newListPrice: `5,000원`,
       newPrice: `4,500원 + 마일리지 250원`,
       usedDirect: `-`,
       usedStore: `-`,
       usedSeller: `700원 (최저가)`,
       bestProduct: `-`,
       betterProduct: `-`,
       goodProduct:`-` 
    }
]
// {
//     thumb: ,
//     name: ,
//     caption: ,
//     newListPrice: ,
//     newPrice: ,
//     usedDirect: ,
//     usedStore: ,
//     usedSeller: ,
//     bestProduct: ,
//     betterProduct: ,
//     goodProduct: 
//  }